### ISSUE TITLE
Creating a REST api with Koa & Node

### ISSUE THREAD

**Issue by gb1** [nottsjs/speakers#1]
Create a simple CRUD api using Node & Koa. Introducing some ES6 features used in Koa e.g Generators

**Comment by iancrowther** [comment]
hey @gb1 thats a fantastic opener :-)  

I really really want to see that talk..

**Comment by gb1** [comment]
Great! Let me know when you have a date/location in mind and hopefully I'll be in Notts (I work away a bit :-) )

**Comment by iancrowther** [comment]
Im thinking October as the Sept one will be a node school.. dates to follow

**Comment by iancrowther** [comment]
Hi @gb1 

Event info can be found at https://ti.to/nottsjs/october-2015

Can I confirm you are still ok to speak?

**Comment by iancrowther** [comment]
Gentle nudge 😋

**Comment by gb1** [comment]
Hey Ian,

I'm working in London on that Wednesday but will be returning that evening,
would possibly be available for a slot towards the end of the evening :-)

Hope that suits,
Gregor

**Comment by iancrowther** [comment]
Your "the" speaker :-)

What time can u be there, it's 15mins walk from mitts station.

I can fill in for a bit with some bits..

**Comment by iancrowther** [comment]
* Notts

**Comment by iancrowther** [comment]
Hi @gb1,

Yes we can put you on last.  Could you give me an eta?

**Comment by iancrowther** [comment]
@gb1 is 20:00 ok?

**Comment by gb1** [comment]
That should be fine Ian.  Travelling from West London so hopefully no rail
delays etc!  Looking forward to it.

**Comment by iancrowther** [comment]
@gb1 - do you know where the meetup is?

34 Stoney Street, NG1 1NB

**Comment by gb1** [comment]
I'm outside!

**Comment by iancrowther** [comment]
@gb1 superb - can you tweet the github links
