### ISSUE TITLE
Android and the Web

### ISSUE THREAD

**Issue by grahamsmith** [nottsjs/speakers#12]
Android is one of the biggest mobile platforms alive. This talk covers different aspects of how Android interacts with the web, from the infamous WebView and ChromeView to load local and internet based content, to using HTML with basic TextViews, and how JavaScript interacts with Android securely. Additionally; how to register an app to respond to a web schema so that an app responds when installed and strategies around to handle this.

**Comment by iancrowther** [comment]
+1 

Is this for Feb/mar or is this a back pocket talk?

**Comment by grahamsmith** [comment]
Shall we do this for March?

**Comment by jonathanKingston** [comment]
Does this make sense as part of the debate, pre amble to educate etc?

**Comment by iancrowther** [comment]
Postponed until @grahamsmith has capacity from work commitments
