### ISSUE TITLE
🔒Front End Security - CSP🔒

### ISSUE THREAD

**Issue by jonathanKingston** [nottsjs/speakers#13]
Securing apps is hard and added to that no one wants to actually buy into securing them either.

I want to run through some quick ways to cut out the risks of apps without having to worry constantly about shipping new code.

I'll talk about upcoming features in CSP if I get time also.

**Comment by iancrowther** [comment]
I have proposed march for two of your proposals, please choose which one you want to do.

my preference is for this one!

**Comment by iancrowther** [comment]
really really want to see this talk!

**Comment by iancrowther** [comment]
can you confirm and we'll lock you in

**Comment by jonathanKingston** [comment]
Talk link: https://github.com/jonathanKingston/talk-nottsjs-csp
Would be good to archive all old slides etc somewhere.
