### ISSUE TITLE
Unity is childs play

### ISSUE THREAD

**Issue by nomad3k** [nottsjs/speakers#14]
This is a talk using JavaScript in Unity to create a simple game, by my 14yo son.  Went very well when the talk was given at Tech Nottingham.

**Comment by jonathanKingston** [comment]
Is June 14th ok?

**Comment by nomad3k** [comment]
Confirming this for June.

**Comment by jonathanKingston** [comment]
Thanks guys. Perhaps put slides here too (who knows we might do a wall of fame one day hah)?
