### ISSUE TITLE
Web components is a way of life

### ISSUE THREAD

**Issue by jonathanKingston** [nottsjs/speakers#15]
See how native web components can work today to improve your website code to what this can expand to in the near future.
This will cover coding practices and how new scripting features will impact your styles.

**Comment by iancrowther** [comment]
looks good to me

**Comment by iancrowther** [comment]
@jonathanKingston has this talk been done yet?

**Comment by jonathanKingston** [comment]
Nup, exclusive to Notts ;). Don't book it for the same as the debate.
Maybe a month or two after that one?

**Comment by iancrowther** [comment]
ok

**Comment by iancrowther** [comment]
@jonathanKingston can we confirm this for Sept then?

**Comment by jonathanKingston** [comment]
@iancrowther I don't have the time to prepare lots of examples for next month I don't think. I could probably do a lightning talk on something if we need one though.
