### ISSUE TITLE
React and Redux from the Trenches

### ISSUE THREAD

**Issue by ajbkr** [nottsjs/speakers#16]
Lessons learned from working with React and Redux for the past 6 months to create an asynchronous, isomorphic, server-side rendered SPA complete with RESTful API powered by Python/Django.

Essentially: dos, don'ts, gotchas, best practice approaches, red herrings, false starts, and evolving practices.

Technologies include webpack, Express, react-router, redux-simple-router, CSS Modules, react-cookie, Mocha/Chai, Babel, ES2015/2016, Immutable, cheerio, etc.

**Comment by cleder** [comment]
:+1:

**Comment by iancrowther** [comment]
looks fantastic

**Comment by iancrowther** [comment]
proposing this talk for May 10th.  Please confirm

**Comment by ajbkr** [comment]
Confirmed.

**Comment by jonathanKingston** [comment]
Added initial description onto https://nottsjs.org/ please confirm if there are any issues etc. /cc @kristianroebuck

**Comment by roebuk** [comment]
Hey, @jonathanKingston 

I've read that slots are 20 minutes. I just wanted to confirm that our slot will be 20 minutes. Also how strict this timing?

**Comment by jonathanKingston** [comment]
Hey!

Slots usually tend to be 30 and it's not strict. We should have enough filler to add time or increase time with questions or other announcements :).

I'll confirm with Greg on how busy he is as which slot may be decided by his schedule and the wifi gods.

**Comment by jonathanKingston** [comment]
Thanks @kristianroebuck and @ajbkr
