### ISSUE TITLE
Javascript Breakfast Club - Workshops

### ISSUE THREAD

**Issue by mathewtrivett** [nottsjs/speakers#17]
Something from the Lean Coffee session from tonight's workshop:

I would be interested to see NottsJS host / run workshops from beginner > intermediate > advanced for people wanting to get into programming / polish their skills / move up the knowledge ladder.

I think most learn best in social environments and through project work, so a bit of learning core principles and then applying them in a real world thing.

Someone mentioned the phrase, "A like code club but for adults", yes! Except with more advanced content developed by the community too.

Someone else also mentioned, "It could be like a Saturday morning thing, with breakfast".  Also yes!

Would be interested in both running a beginner's workshop and working with NottsJS organisers to find a venue.

If there were other workshops that were a bit more hands on, what sort of things would you want to learn?  What sort of projects would you want to have a go at?  What do you think of the idea?

**Comment by jonathanKingston** [comment]
Can and will help. Happy to run courses in JS for people who have never coded as I think there is value in that.
But yeah let me know :+1:

**Comment by iancrowther** [comment]
@mathewtrivett - Why not just make this nodeschool nottingham? 

You dont have to follow the courses by the book, add the variety and colour you want to. I suggest this as there is a ton of community content already and people around who have experience delivering it.

I'm sure JH would help as well as the NottsJS orgs

**Comment by mathewtrivett** [comment]
@iancrowther its true.

The more I've thought about it...the more I think that nodeschool is great.  Still think that having a Saturday morning / breakfast flavour might make it a more accessible to some if done right.

I think I got a little overexcited with the name...maybe BreakfastJS could be something else...

Happy to explore organising

**Comment by iancrowther** [comment]
no worries.

Are you going to do a talk in this? if not, I do think this thread should be moved out of our speaker proposals repo into feedback or somewhere where the discussion can continue
