### ISSUE TITLE
Lightning debate: web vs native

### ISSUE THREAD

**Issue by jonathanKingston** [nottsjs/speakers#18]
@grahamsmith and I love talking about web vs native. There is probably a good 'leadership debate' style we could use here of pre arranged questions on what is the differences (I think we could make it fun but actually informative).

There is a whole lot of room in this style from: small demos of the latest tech to answering questions about what the differences are and why it matters.

**Comment by iancrowther** [comment]
i want to see this..

**Comment by iancrowther** [comment]
proposed for May 10th, pls confirm

**Comment by jonathanKingston** [comment]
Fine by me if it is after 6. Need to have a meeting with Graham first to
decide on the contents.

**Comment by jonathanKingston** [comment]
Graham can't make May and because of how the days fall on the Tuesday I can't attend June.

**Comment by jonathanKingston** [comment]
@grahamsmith July is ok right?

**Comment by jonathanKingston** [comment]
I suggest we move this to August to account for the double event in July. That ok @grahamsmith?

**Comment by Codesleuth** [comment]
Moving this to September.

**Comment by iancrowther** [comment]
Postponed until @grahamsmith has capacity from work commitments
