### ISSUE TITLE
Playing with... WebRTC

### ISSUE THREAD

**Issue by mozmark** [nottsjs/speakers#19]
WebRTC is useful tech... but who cares about useful? Let's do something fun!

Let's take a look at WebRTC. It will be weird. Hopefully it will be fun. You might even learn something.

**Comment by mathewtrivett** [comment]
Would love to see this...

**Comment by iancrowther** [comment]
group hack or instructor-led, I love the kamikaze chaos of "let just build something.."

**Comment by mozmark** [comment]
A group hack could be fun - though I'm not sure how much we can achieve in a single session (especially if people are new to the tech).

**Comment by jonathanKingston** [comment]
We normally do two part events, would it make sense to do your talk and a super basics workshop on WebRTC? (Not sure how that works with time @iancrowther)

**Comment by mozmark** [comment]
That could work?

**Comment by jonathanKingston** [comment]
July or August as a schedule? (As I know you are at the work week)

**Comment by mozmark** [comment]
I'll check dates later on.

**Comment by jonathanKingston** [comment]
@iancrowther and et all. I suggest we make this a double event with workshop and talk.
Workshops seem to bring in the crowds and Mark seems happy to be twisted to do that ;).

**Comment by iancrowther** [comment]
sold

Can you add a separate issue for the workshop so we can discuss?
