### ISSUE TITLE
Exploring using the Web Audio API to allow people to hear charts and plots

### ISSUE THREAD

**Issue by matatk** [nottsjs/speakers#22]
Charts and plots are engaging and widely used on the web, but present barriers to people with vision impairments, as well as those who cannot use a mouse, or are using small devices.

A lot of research has been done into using sound as as a means of communicating information to people and the benefits this can bring to people in various situations. Now that the Web Audio API is well-supported, some really interesting stuff is being done with it, and I thought it could be an ideal way to make charts and plots more accessible.

I and developing library called AudioChart that provides an aural, keyboard-accessible means to experience charts and plots. I have given similar talks at other events ( http://www.csun.edu/cod/conference/2016/sessions/index.php/public/presentations/view/269 and http://www.meetup.com//London-Accessibility-Meetup/events/229039168/?showDescription=true ) and would cover areas such as the accessibility barriers that charts and plots present, as well as the technical nature of AudioChart - could tweak this to be more techy as it seems to be a development-focused audience.

You can find some basic demos of AudioChart at: http://matatk.agrip.org.uk/audiochart/

It is undergoing active development and I'm hoping to get to a level where user research can be done, to assess how useful it is.

P.S. Some of this stuff is a spiritual successor to work I used to do on accessible gaming ( http://agrip.org.uk ), though that's not Web/JavaScript-related, and I'm not sure how much of it I could demonstrate at the moment, but I may be able to show a bit of it as another application of sound.

**Comment by jonathanKingston** [comment]
@grahamsmith can we swap this for our talk in August? I think it has some real value over ours and we haven't really done anything yet. (looks like we will have to do that anyway... lets push this for September if we can).

**Comment by grahamsmith** [comment]
Sure :)

**Comment by matatk** [comment]
Just to check I'm reading this right: does this mean I'm on for the August meet (i.e. the 9th)?

**Comment by Codesleuth** [comment]
It does look that way - but the conversation is really confusing.

**Comment by Codesleuth** [comment]
Actually, we have 2 proposed for August already, so it seems not.

**Comment by matatk** [comment]
Righto. If it's of use, regarding timing info: I would be available for the rest of the year (at least), but not in October (I believe the October one would be the 11th; just had a work commitment crop up then).

**Comment by Codesleuth** [comment]
How available would you be if we need you for August? Do we need to let you know soon? Just trying to clear this up with the rest of the team, as I'm pretty confused myself right now.

**Comment by matatk** [comment]
Sorry for the laggy reply; I probably could do August (the 9th, right?) though that would be quite tight so if it's at all possible to know this week (I mean before next week) that would help ensure I have enough notice to make arrangements.

**Comment by matatk** [comment]
Hi, just a quick one to ask if you'd been able to find out if you need me next week -- I can probably still arrange this if you can let me know within the next couple of days, but after that it'd be really quite tight.  Hope to see you soon, if not even sooner :-).

**Comment by Codesleuth** [comment]
I was hoping you're still available - it would be _fantastic_ if you can still make this talk for next week! That is assuming that you think it's suitable for a ~1 hour slot?

The reason I ask is because a practical session of some sort for this talk this would be great - I know a lot of our attendees would like to get stuck into something.

**Comment by matatk** [comment]
I will double-check with my employer and figure out travel arrangements, though I expect both to pan out OK; I'll do my very best to confirm for sure tomorrow evening.

I already have slides from a previous instance of the talk; in terms of practical stuff, there's the 'hello world' tutorial (available on the website above).  I don't think there will be a problem filling a one-hour slot (as it has covered a 50min one before).

Once again: I'll start making plans and will try very hard to be able to confirm tomorrow evening.

**Comment by matatk** [comment]
Hi, I have confirmed I can get the travelling time off work, so looks like I am on for this, but just have a few things that we need to check/confirm…
1. The demo I am giving (and practical bit, for anyone who wants to follow along) requires an Internet connection (this is due to the Google Chart Tools API requiring this in its terms and conditions).  I can probably tether to my 'phone for mine if needed, but just want to give this warning.
2. I gathered some info from @jonathanKingston (in a separate channel) about the travel bursary; may I continue talking to Jonathan about this, or use the email address on this repo's README?  I will book travel ASAP, just finalising the times.
3. There is [currently a problem with the railway](http://www.nationalrail.co.uk/service_disruptions/144860.aspx), which I assume will be fixed by next week; I am looking out for an estimated date for re-opening.  It would likely be a showstopper as far as my travel goes if it's not open again by next week, though I think that's unlikely; certainly hope so for those who have to use it every day.
4. It won't be possible for me to show the accessible gaming stuff next week (I would've run out of time anyway, especially if doing some live/practical stuff with AudioChart); that is kind of a different story anyway (and less JavaScript-y) :-).

I think that's it; will continue making arrangements and post back if necessary.  Looking forward to meeting you all :-).

**Comment by jonathanKingston** [comment]
@matatk we will love you have you, sorry there has been so much confusion with this month.
1. We have wifi and 3g if we need it. We are sorted for internet
2. Anyway feel free to continue reaching out to me on twitter etc for the travel, that isn't an issue.
3. Sure let us know as soon as you hear anything please, sorry again this has been so tight etc.
4. Sure, but it's the coolest sounding thing ever and I would love to hear all about it some time 👍 

Thanks again!

**Comment by matatk** [comment]
Great; sounds good and no worries :-).

Looks today like they expect the railway line to remain open at least for the trains I'd need, so I think we can assume that'll be OK.  I'll contact you offline regarding the travel when I have a little bit more info on my end; thanks!

**Comment by Codesleuth** [comment]
Hi @matatk, we've just published your talk details. Can you take a look? If you have any issues, please get in touch! https://nottsjs.org/

**Comment by matatk** [comment]
@Codesleuth looks good; thanks :-).

**Comment by matatk** [comment]
Thanks very much to you all for a warm welcome and very interesting ideas for AudioChart; to @ruth-connect for the React/Java presentation and everyone who was able to make it to the pub for a fun discussion afterwards :-).
