### ISSUE TITLE
Automating Photoshop with nodejs

### ISSUE THREAD

**Issue by darshanmarathe** [nottsjs/speakers#24]
# Automation of Photoshop PSD file with node.js

We will write a plugin which will allow designers to separate the data from bulky PSD files and it will compile the PSD files with data and create png files for sending it to client 
Possible use cases
- Creating different versions of content
- Multi language support 
## Possible Automation and plugin
-  Mail Merge
- Automation of site which provide design on tshirts 
- Seprating content with PSD file so they can be versioned

**Comment by Codesleuth** [comment]
Closing (hopefully deferred!) since we couldn't fit this talk in.
