### ISSUE TITLE
Progressive Web Apps (or just service workers)

### ISSUE THREAD

**Issue by DanIanShea** [nottsjs/speakers#25]
“The application cache is a douchebag" - Jake Archibald.

Web apps can be pretty cool, but we could be making them even cooler. Browsers are leveling up by adding functionality to enable a user experience akin to using a native mobile application.

Enter the new buzz-phrase of the moment… Progressive Web Apps!

We’ll explore how we can take our web apps offline but most importantly why you should care about this! Features such as service workers, background sync, push notifications, save to homepage and splash screens are pushing forward the frontier of UX in the web.

This talk is about sharing the knowledge gained from FullStack 2016 conference and the lessons learned from implementing the features into real web applications. The goal is to provide more than just a high level overview. You should be able to walk away confident that you can implement these features into your own web apps straight away.

Dan Shea is a Senior Software Developer at UNiDAYS. Professionally he concentrates on web apps and web services leveraging .Net technologies. In his own time he likes to gain hipster dev cred by hacking away with node and angular using an ancient linux laptop. When the moment strikes he likes to build crappy robots and make even crappier games.

-- Side note, Graham asked if I'd like to give a talk on service workers as I'm due to give the above talk to Dot Net Notts. I can adjust the talk to focus more on service workers if needed and abandon other elements surrounding PWA.

**Comment by jonathanKingston** [comment]
Sounds good to me, just service workers may be lots more research into design patterns rather than just a high level of all the features perhaps?

**Comment by grahamsmith** [comment]
We should do a workshop after maybe?

**Comment by DanIanShea** [comment]
Hey, Cheers for the quick replies.

Happy to do progressive web apps over service workers alone.

My thoughts are that I'll cut down the preamble. Do a live demo, show more examples, then move onto a workshop for the latter half of the session.

My main ambition with this talk is to get people implementing it asap on their own projects and or employers sites, as it's relatively easy to get basic functionality in place.

Below is the contents slide for the talk:
- Act One: Why should I care?
  ​Somebody please think of the users
- Act Two: Okay I care now, what's available?
  Live browser features
- Act Three: Show me the codes!
  Production Demo
  Live coding + samples
- Act Four: Show me moar!
  In dev browser features

**Comment by grahamsmith** [comment]
Seems well thought out to me. Maybe we can get this in for October?

**Comment by Codesleuth** [comment]
@DanIanShea how would you feel about presenting this talk in October? I'll flag you as proposed so we can get the ball rolling.

**Comment by DanIanShea** [comment]
Yeah happy to give the talk in October. It's definitely the 11th? I ask as I am on holiday 1st - 8th.

**Comment by Codesleuth** [comment]
Yep, second Tuesday in October. I'll move you to accepted. Cheers!

**Comment by Codesleuth** [comment]
@DanIanShea Do you have a few paragraphs about yourself that I can post on the website? Also any contact you would like to be announced such as Twitter or a website.

**Comment by Codesleuth** [comment]
Actually I just realised you did post a bio in the issue - but I would be grateful for links if you have some.

Also, happy with the title "Exploring Progressive Web Apps"?

**Comment by DanIanShea** [comment]
Personal Site:
https://www.danthenortherncodemonkey.com/

Personal Site Github (service worker running on it):
https://github.com/DanTheNorthernCodeMonkey/DanTheNorthernCodeMonkey.github.io

Both need some TLC, which will be happening this week.

Slides:
http://slides.com/dancodemonkey/deck#/

 Happy with the title.

**Comment by DanIanShea** [comment]
The fullstack conference hyperlink on your site is incorrect. This one should be correct:
https://skillsmatter.com/conferences/7278-fullstack-2016-the-conference-on-javascript-node-and-internet-of-things
