### ISSUE TITLE
Elm

### ISSUE THREAD

**Issue by ghost** [nottsjs/speakers#27]
http://elm-lang.org

Elm is a functional, declarative programming language that compiles to JavaScript. It's used to make client-side web apps, and I've been using it to build a donations application. I'll show you The Elm Architecture, a nestable pattern for building applications. Elm has a neat inferred type system that stops users running into errors. We'll look at how a pure functional language does side effects like HTTP requests and websockets. We'll also look at how Elm handles uncertainty, the use of partial function application for reusable views, how it interacts with JS libraries, and how data immutability gives you undo/redo for only a few lines of code. Bring your laptop!

**Comment by Codesleuth** [comment]
This is awesome. I'll propose it for January, but depending on discussions of December we might ask you to do it sooner. Happy with that?

**Comment by ghost** [comment]
Sure thing! Great.

**Comment by Codesleuth** [comment]
Hey Will, I hope your Christmas and New Year has gone well and you're refreshed for 2017?
Just wanted to check if you are prepared to give your talk on the 10th, or if there's anything we can do to help you get prepared.

Can you confirm you're set for next Tuesday? I'll start the ball rolling on everything if you are.

Cheers! 🎉

**Comment by ghost** [comment]
Hey David. Yep, will be ready by next Tuesday. It might help to run the talk outline by someone, in case I've missed anything important for the audience.

**Comment by Codesleuth** [comment]
I'm free for a chat, whether in person or on video & screen share if you need. But if you'd like to speak to someone who knows more than the zero I know about Elm, I can ask them to speak to you? (@hawx)

Also, can you please link to, or post a bio with some profile links for the website?

**Comment by ghost** [comment]
Thanks. Video & screen share would be good. I'll pull it together and get back to you soon.

**Comment by ghost** [comment]
Will it be 20 minutes? I think the NottsJS talks I've been to before have been longer, that's all.

**Comment by Codesleuth** [comment]
Half an hour plus questions will usually fill the first half of the evening, about 45 mins. If you think your talk will be short, we can try allocate a second talk or activity for the night, but given the topic I'd say some sort of Elm practical session would be fantastic for people to get involved in. How's that? Do you have time to prepare anything?

**Comment by ghost** [comment]
Yeah I'm doing live coding so it'd be no trouble to extend that to a practical session with elm-lang.org/try.

**Comment by Codesleuth** [comment]
Would you be able to post or link to a bio with some profile links so I may post them on the nottsjs website?

**Comment by willnwhite** [comment]
May I just write my bio here for you to copy and paste?

**Comment by ghost** [comment]
Hey David, here's my bio. Happy for you to link to my GitHub.

I started out as a doctor interested in public health, but found its scope to be too limited. Now I'm writing software. I'm working on a donations application that will build wealth redistribution into everyday transactions. As far as I know, [Helpfreely](https://www.helpfreely.org/) have made the most progress in this direction so far, so check them out if you'd like online shops to donate to your causes when you buy from them. I hope to be working with them soon.

I'm also co-administering the [Nottingham chapter of Free Code Camp](https://www.facebook.com/groups/free.code.camp.nottingham/). Free Code Camp is a free online course whose members learn to code and help nonprofits.

I read about Elm in late 2015, and I've been using it for the last six months or so. Before then I was using React/Redux and vanilla JS.
