### ISSUE TITLE
Node in the AWS Cloud - PARTICIPATION

### ISSUE THREAD

**Issue by nomad3k** [nottsjs/speakers#28]
Use Web API and Lambda to construct a REST API that runs on NodeJS.  I'd like it to be a participation event where the group creates the API, which effectively allows a client site/app to consume it.  Very much a starting point, and could be a basis for further AWS talks, such as how to secure it.

**Comment by ghost** [comment]
Also, have you seen [Serverless](https://serverless.com)? It's a nice framework for building apps using Lambda and eventually other function-as-a-service services. It may or may not make it easier for us (I'm not experienced with Lambda, but Hello World was easy with Serverless).
