### ISSUE TITLE
Introduction to TypeScript

### ISSUE THREAD

**Issue by Codesleuth** [nottsjs/speakers#4]
Discover what TypeScript is, how it's useful, and how to get started using the language in new and existing projects.

I'd like to present the talk as a quick-start session which guides the audience through the basics of what the advantages are of TypeScript, and then how they can make the most of these advantages _today_.

If you'd like to combine this with a practical session, I can prepare a workshop for participants to demonstrate the points covered in the talk.

**Comment by iancrowther** [comment]
yay

**Comment by iancrowther** [comment]
let me know if this date works for you

**Comment by Codesleuth** [comment]
That's fine. The talk is ready, and I gave it at Esendex last month. It's around 15 minutes right now but I can pad it out a bit more quite easily. If you'd like it sooner, just let me know, otherwise I'm all set for Feb.

**Comment by iancrowther** [comment]
awesome.  We have had a lot of talks submitted which is fantastic

**Comment by Codesleuth** [comment]
Should this be labeled `Accepted Schedule`?

**Comment by joemckie** [comment]
Hey David - marking it as accepted now, you still good for the 10th?

**Comment by Codesleuth** [comment]
Yep no problem. I'm aiming for a 20 min talk right now (somebody mentioned that I think?) if you need more content that's fine, just let me know.

**Comment by iancrowther** [comment]
@Codesleuth everything on track still?

**Comment by Codesleuth** [comment]
Still a bit deaf but getting better! How long do you want the talk to be? I plan to demo too (wish me luck!)

**Comment by iancrowther** [comment]
min 20 mins, but you know the setup, whatever works
