### ISSUE TITLE
Why would I ever Elm

### ISSUE THREAD

**Issue by hawx** [nottsjs/speakers#42]
A look at some of the many things that can be meant by "functional programming" and to what degree that applies to JavaScript. Then a look at how these ideas, which are present in Elm, allow us to easily write safe front-end applications, with comparisons to other frameworks and packages such as React and Redux.

Also planning a workshop where we break into groups based on frameworks of choice and discuss the good and bad between re-implementations of a simple Elm app in Angularjs and React.

**Comment by BigWillie** [comment]
+1, would love to see this :)
