### ISSUE TITLE
Talk: Saving the world with JSON schema

### ISSUE THREAD

**Issue by robredpath** [nottsjs/speakers#43]
I work for http://opendataservices.coop/ - we're a tech co-op who help people and organisations publish and use open data in a variety of fields, including international development, government procurement and philanthropy. We do it to help those organisations have an impact on the world - to make people's taxes go further, to stop corruption, to make aid more effective, and to help make sure that charity money goes where it's needed most. Underpinning this work is a ton of JSON Schema (and some XML Schema, if you dig around the back of our closet). I got chatting to @Codesleuth at Tech Notts a few weeks ago about how this could be a talk, so here's the proposal! 

Briefly, I'd cover:
- Who I am, who I work for, why tech co-ops are awesome [ 2 mins ]
- What open data is, what open data standards are, why the whole thing is good for the world [ 2 mins ] 
- Some technical detail of how our standards are structured, get some JSON Schema on screen [ 5 mins ]
- Show off our (open-source) documentation stack for generating docs from JSON Schema [ 5 mins ]
- A couple of examples of where having standardised open data has made life better in cities around the world [ 5 mins ]
- A bit of a pitch for a nebulous idea around open data in Nottingham I'm (slowly) starting to revive [ 1 min ]

**Comment by Codesleuth** [comment]
Thanks Rob, loving the synopsis here! As it is, I'd love to have the talk in May (as we discussed before). Are you still available?

I see the value of the talk centres around standardisation and how you've achieved it. Would it be possible to add in some lessons of your experiences of where non-standardised data has caused problems, and how you solved it? Are there any other things you could speak about regarding lessons in the process of building this?

**Comment by robredpath** [comment]
8th of May, right? I'm at Agile Manchester, unfortunately! 

I can certainly talk more about the issues around completely non-standardised data and why close enough isn't good enough when it comes to standardisation, with real examples. And I can talk a bit more about the political environment around making standards work - as usual, the tech is the easy bit, the humans are the hard bit!

**Comment by Codesleuth** [comment]
Hey @robredpath! This sounds good to me; can we book you in for June 12th?

**Comment by robredpath** [comment]
@Codesleuth sure thing; it's in my calendar now!

**Comment by Codesleuth** [comment]
Hey @robredpath, your talk is announced here: https://nottsjs.org/#2018-06-12-saving-the-world-with-json-schema

Can you give it a read through and check it's OK for you?

**Comment by robredpath** [comment]
Looks good @Codesleuth!
