### ISSUE TITLE
May Lightning Talks list

### ISSUE THREAD

**Issue by Codesleuth** [nottsjs/speakers#45]
This issue here to capture [May 8th's Lightning Talks](https://nottsjs.org/#2018-05-08-lightning-talks). Post your talk idea as a comment and I'll keep the proposed schedule here!

1. @cruxicheiros with "Why Ants are Really Interesting"
2. @mozmark with "Same Site Cookies"
3. @codesleuth with "WALT Vinegar"
4. @cruxicheiros with "Solving Non-problems with Code"
5. @codesleuth with "Contain Your Containers!"
6. TBD
7. TBD

_Note that I will bump my own talks off the list in favour of yours, so please don't think that you won't get a spot!_

Handy template:

```
| Field | Value |
|-|-|
| Proposal | **_title_** |
| Summary  | _summary_ |
| Duration | 5/10/15 minutes |
```

**Comment by Codesleuth** [comment]
| Field | Value |
|-|-|
| Proposal | **WALT Vinegar** |
| Summary  | Web Assembly has come leaps and bounds in the last few months, and with this comes tooling! Meet [WALT](https://github.com/ballercat/walt), a new JavaScript-like syntax for Web Assembly! |
| Duration | 15 minutes |

**Comment by Codesleuth** [comment]
| Field | Value |
|-|-|
| Proposal | **Contain Your Containers!** |
| Summary  | Docker as tooling is everywhere. It solves many problems, and mostly it's used without thought. However, building your own images can be a tricky task, especially if you build them often and publish each build to a private registry - this can grow very large very quickly! Controlling the size of your containers can be an arcane task, but there are some simple tricks to get them lean. Let's take a look at some of easy and quick ways to improve your image sizes! |
| Duration | 15 minutes |

**Comment by cruxicheiros** [comment]
| Field | Value |
|-|-|
| Proposal | **_Why Ants are Really Interesting_** |
| Summary  | _ANTS. This isn't actually tech related but I'm 100% willing to talk about it._ |
| Duration | 5 minutes |

**Comment by cruxicheiros** [comment]
| Field | Value |
|-|-|
| Proposal | **_Solving Non-problems with Code_** |
| Summary  | _Useless websites,and why they're awesome._ |
| Duration | 5 minutes |

**Comment by mozmark** [comment]
| Field | Value |
|-|-|
| Proposal | **_Same Site Cookies_** |
| Summary  | _All about Same Site Cookies: What they are and why you should care_ |
| Duration | 5 minutes |

**Comment by Codesleuth** [comment]
Looking like a great line-up, keep them coming!
