### ISSUE TITLE
Node Application Performance

### ISSUE THREAD

**Issue by joshghent** [nottsjs/speakers#46]
Hi Guys,
Been meaning to submit this for a while!

Performance is a seldom thought of principal of software development and with the rise of serverless technologies, performance really matters more than ever! This talk is to discuss improving node application performance whether a express API or other backend service.
Although this talk is geared towards NodeJS (since it's a JS meetup), these principles can apply anywhere!

I’d like to cover in this talk
- Nginx - gzip
- Application cache - redis
- Compression headers
- Cluster
- NODE_ENV=”production”
- DB Connection Pooling
- Precompiled binaries
- Async all the things!
- Rate limiting
- Reduce the size of bundles - to reduce the impact of cold starts (serverless) ❄️ 
- Monitor!

**Comment by Codesleuth** [comment]
Hey Josh, sorry I've left this hanging!
How do you feel about 10th July? And how long do you think you can fill? There's a lot here and I wonder if you're maybe covering a bit too much. Some of those bullet items could be talks on their own, but if you want to cover it all then go ahead!

**Comment by joshghent** [comment]
@Codesleuth Don't think I will be able to prep in time for the July meetup unfortunately. In terms of time, I will fully prep and time it and update you. May have to cut some stuff out!

**Comment by Codesleuth** [comment]
OK, that's fine. I'll put you in as proposed for August, and let's see if you can make that. Sound good?

**Comment by Codesleuth** [comment]
Hey Josh, how's the planning going for this? Are you on track for August?

**Comment by joshghent** [comment]
Hi mate, yes should be good. I'll update you with slides in a couple of weeks time (maybe this week if I have time). Thanks a lot! Will keep you posted. Don't think I'll have time to cover all that I put originally, but just deciding on what to cut!

**Comment by joshghent** [comment]
Slides can be found here: https://github.com/joshghent/talks/tree/master/lightning-performance
