### ISSUE TITLE
Doug Sillars on Performance of Images and Video Delivery

### ISSUE THREAD

**Issue by Codesleuth** [nottsjs/speakers#48]
_Placeholder for Doug's talk_

See https://dougsillars.com and https://www.youtube.com/watch?v=a5orCnxIwIA

**Comment by dougsillars** [comment]
Abstract: The average website page weight is 50% images and 25% video. As the images and videos delivered to mobile devices get larger and larger, the load time of websites gets slower and slower. Further complicating matters, there are thousands of screens and devices with varying resolutions and CPU power that receive this content. In this talk, we’ll examine strategies to send the perfect image or video to every device, ensuring a fast, beautiful rendering of your content. We’ll look at how to test our content, and describe responsive images, delivering progressive images, and finally optimizing all of this content for fast delivery to each screen. Attendees will walk away with a better understanding of how to efficiently deliver beautiful images to every device that accesses their content.

**Comment by dougsillars** [comment]
bio:
Doug is is a freelance mobile performance expert, having helped thousands of developers speed up their mobile apps and websites.  A Google Developer Expert and the author of O’Reilly’s “High Performance Android Apps,” Doug has spoken at developer conferences in the US and Europe, and blogs regularly at dougsillars.com. He is currently working as a freelance digital nomad, traveling with his family in Europe.
