### ISSUE TITLE
Javascript & SEO - Talk

### ISSUE THREAD

**Issue by templarwilson** [nottsjs/speakers#51]
My talk will be focused on modern Javascript frameworks and why they're failing in Google search. The aim of the talk will be to educate developers who are unfamiliar with these issues but also to encourage SEO & Developers to work together. The talk will be pro JS and maybe a little anti Google.

More and more of our clients are using Javascript frameworks which have caused issues with Google's web rendering service. The talk will go over how Javascript can cause issues with Google and how you can make sure it's crawler & render friendly.  I'll also be running through examples of projects that we've been working and how we have worked with javascript frameworks to ensure websites are optimised for search. 

I work for a digital marketing agency called Impression in Nottingham city centre. We were named best large SEO agency at the European Search Awards 2018 and my recent JS/SEO campaign has been listed for most innovative campaign at the UK Search Awards 

Impression & Cromwell - How we REACTed to the JavaScript landscape (Hopefully you appreciate the pun)
https://www.searchawards.co.uk/2018-shortlist

**Comment by Codesleuth** [comment]
Thanks for the proposal! This sounds really interesting, and we'd love to host this. Can you send me an email so we can speak about slotting you in? You can [get it from my user page](https://github.com/Codesleuth).
