### ISSUE TITLE
Indie what?

### ISSUE THREAD

**Issue by hawx** [nottsjs/speakers#52]
An intro to how we can use IndieWeb standards to build "social" websites that allow people to own their own content. Something like,

- Logging in with your website
- Discovering profile information instead of filling out yet. another. name. field.
- Posting to another site while owning your data
- and maybe more if I can think of anything :rocket:

**Comment by Codesleuth** [comment]
Sorry, accidentally pressed an automatic reply on my watch!

**Comment by Codesleuth** [comment]
Very interesting topic and would love to see where this goes. OK for January 8th?

**Comment by hawx** [comment]
:+1:
