### ISSUE TITLE
SVG + JS = 💖

### ISSUE THREAD

**Issue by edent** [nottsjs/speakers#54]
As discussed on Twitter, I'd like to come up to Nottingham to talk about the cool things you can do when you mix Scalable Vector Graphics with Javascript.

I have given a version of this talk at JsOxford https://www.youtube.com/watch?v=iSGww5ZSnqA

And LondonWebPerformace https://www.youtube.com/watch?v=eTQn-CwgFgA

My contact details are at https://edent.tel/

**Comment by Codesleuth** [comment]
YES! This will be great! I will contact you on Twitter DM to arrange proposed dates 👍
