### ISSUE TITLE
Intro to Vue.js

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/speakers#55]
Title: Introduction to Vue.js
Body: An overview of Vue.js core features & patterns followed by some demo's to show how easy it is to get started.  Demo's will touch on Vuetify & cypress.io.

Bio: A Node.js engineer who dabbles with DevOps & Frontend.  A big fan of keeping it simple and adopting web standards.

**Comment by Codesleuth** [comment]
@iancrowther can you do June instead of July? I have #54 for July so it'd be better if I could schedule you for June or August.

**Comment by iancrowther** [comment]
June is fine

**Comment by Codesleuth** [comment]
Could you post a talk summary and a bio for yourself so that we can prepare the website and meetup event with the details?

Also what's your expected runtime?
