### ISSUE TITLE
No Service

### ISSUE THREAD

**Issue by ukmadlz** [nottsjs/speakers#6]
No matter where you look in technology, everything has an online component. But with the advancement of web technologies and mobile apps, offline is becoming a key characteristic. This talk covers what's necessary to make a WebApp offline, and some nifty stuff to help along the way.

**Comment by iancrowther** [comment]
@ukmadlz next month we'll do some hacking and in December we'll all be getting drunk so that leaves Jan if your ok with that

**Comment by ukmadlz** [comment]
Seems fine by me. You mind bringing it back up in Dec?

**Comment by iancrowther** [comment]
@ukmadlz were going to take December off.  So the event following November will be in Jan.  

December is traditionally a bad month for meetup as everyone is focused on xmas.

**Comment by iancrowther** [comment]
Can I finalise Jan?

**Comment by ukmadlz** [comment]
Yeah, what's the date in Jan so I can add it to the calendar?

**Comment by iancrowther** [comment]
Jan 13th - its the milestone attached to the issue
