### ISSUE TITLE
LEAN COFFEE for JS Devs

### ISSUE THREAD

**Issue by unidaysgraham** [nottsjs/speakers#7]
Because LEAN COFFEEs are great and could be a great mechanism to spark interesting talk, could I propose we do one in January.

For those who haven't experienced one:

- Everyone chooses something they want to talk about (on a similar subject.. say JS related?)
- We collate
- We vote on the options
- Highest voted items go first until the time runs out

Note - there are variations on this. We could get subjects via Twitter before hand and on entry people could vote?

**Comment by iancrowther** [comment]
w00t
