### ISSUE TITLE
By Your Command

### ISSUE THREAD

**Issue by chriskempunidays** [nottsjs/speakers#9]
Taking the C from CQS.  Look at why you'd want to adopt a Command based UX model, what benefits they bring to an organisation and also what costs there are.  There's no coding, just looking at some of the wider implications of pushing away the CRUD model.  Simplicity, Intent, Clarity and Reduced Training.  Will be working from examples that came out of real HR projects and compare how existing solutions were solving the problem.

**Comment by jonathanKingston** [comment]
Is June 14th ok?

**Comment by jonathanKingston** [comment]
Thanks guys. Perhaps put slides here too (who knows we might do a wall of fame one day hah)?
